export const FETCH_PLACE_TYPES = 'FETCH_PLACE_TYPES';
export const ADD_PLACE_TYPES = 'ADD_PLACE_TYPES';
export const UPDATE_PLACE_TYPES = 'UPDATE_PLACE_TYPES';
export const DELETE_PLACE_TYPES = 'DELETE_PLACE_TYPES';
export const EDIT_PLACE_TYPE = 'EDIT_PLACE_TYPE';